name: Create Release

permissions:
  contents: write

on:
  push:
    tags: "*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate Tag
        id: validate-tag
        run: |
          if [[ ! "${{ github.ref }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "valid_semver=true" >> "$GITHUB_OUTPUT"
          else
            echo "valid_semver=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.validate-tag.outputs.valid_semver == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref }}
          generateReleaseNotes: true
