name: DocC Release All

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  docs:
    uses: ./.github/workflows/docc-release.yml
    with:
      target: VaporTestingSocketServer
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
