name: Main Commit

permissions:
  contents: read
  pages: write

on:
  push:
    branches:
      - main

jobs:
  docs:
    uses: ./.github/workflows/docc-release.yml
    with:
      target: VaporTestingSocketServer
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
